apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-sunset-setting
spec:
  forms:
    - group: appearance
      label: "主题"
      formSchema:
        - $formkit: radio
          name: color_scheme
          label: "默认配色"
          value: system
          options:
            - label: "跟随系统"
              value: system
            - label: "明亮"
              value: light
            - label: "深色"
              value: dark
        - $formkit: color
          name: accent_color
          label: "强调色"
          value: "#c43d83"
    - group: index
      label: "首页设置"
      formSchema:
        - $formkit: attachment
          name: background_image
          label: "首页背景图"
          accepts: 
            - image/*
          help: "建议使用横向图片，宽度至少1920px"

    - group: footer
      label: "页脚"
      formSchema:
        - $formkit: text
          name: icp
          label: "ICP备案号，若留空则不显示"
          value: ""
          placeholder: 京ICP备12345678号

        - $formkit: text
          name: public_security
          label: "公安备案号，若留空则不显示"
          value: ""
          placeholder: 京公网安备11010802000001号


