apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-pinboard
spec:
  displayName: Pinboard
  author:
    name: Your Name
    website: https://github.com/YourName
  description: A starter theme for Halo.
  logo: /themes/theme-pinboard/assets/icon.svg
  homepage: https://github.com/halo-sigs/theme-astro-starter
  issues: https://github.com/halo-sigs/theme-astro-starter/issues
  settingName: theme-pinboard-setting
  configMapName: theme-pinboard-configMap
  version: "1.0.0"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
  customTemplates:
    page:
      - name: link
        description: 友链页模板
        file: link.html
      - name: immich
        description: Immich 图库页模板
        file: immich.html